# Unique name for this workflow
name: CI on PR

# Definition when the workflow should run
on:
    workflow_dispatch:
        inputs:
            prerelease:
                description: 'Run on a prerelease org?'
                required: false
                type: boolean
    pull_request:
        types: [opened, edited, synchronize, reopened]

# Workflow environment variables
env:
    # Is the PR base branch a prerelease branch
    IS_PRERELEASE: ${{ startsWith(github.event.pull_request.base.ref, 'prerelease/') || inputs.prerelease  }}

# Jobs to be executed
jobs:
    # Dummy job used to skip CI run on automated PRs
    skip-ci:
        if: github.actor == 'trailheadapps-bot'
        runs-on: trailheadapps-Ubuntu
        steps:
            - name: Noop
              run: |
                  echo "Skipping CI run for automated PRs."

    # Formatting and linting only runs on human-submitted PRs
    format-lint-lwc-tests:
        if: github.actor != 'trailheadapps-bot'
        runs-on: trailheadapps-Ubuntu
        steps:
            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            # Install Volta to enforce proper node and package manager versions
            - name: 'Install Volta'
              uses: volta-cli/action@v4

            # PREREQUISITES - Only needed if the runner doesn't already satisfy these requirements.
            - name: Ensure node v20.9.0 or greater
              uses: actions/setup-node@v4
              with:
                  node-version: '>=20.9.0'
            - name: Ensure java v11 or greater
              uses: actions/setup-java@v4
              with:
                  java-version: '>=11'
                  distribution: 'zulu'
            - name: Ensure python v3.10 or greater
              uses: actions/setup-python@v5
              with:
                  python-version: '>=3.10'

            - name: Install Salesforce CLI
              run: npm install -g @salesforce/cli@latest

            - name: Install Latest Salesforce Code Analyzer CLI Plugin
              run: sf plugins install code-analyzer@latest

            - name: Run Salesforce Code Analyzer
              id: run-code-analyzer
              uses: forcedotcom/run-code-analyzer@v2
              with:
                  run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json
                  results-artifact-name: salesforce-code-analyzer-results
                  github-token: ${{ github.token }}

            - name: Check the Outputs to Determine Whether to Fail
              if: |
                  steps.run-code-analyzer.outputs.exit-code > 0 ||
                  steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
                  steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
                  steps.run-code-analyzer.outputs.num-violations > 10
              run: exit 1

            # Cache node_modules to speed up the process
            - name: 'Restore node_modules cache'
              id: cache-npm
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-${{ env.cache-name }}-
                      npm-

            # Install npm dependencies for Prettier and Jest
            - name: 'Install npm dependencies'
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: HUSKY=0 npm ci

            # Prettier formatting
            - name: 'Code formatting verification with Prettier'
              run: npm run prettier:verify

            # Lint LWC / Aura
            - name: 'Lint Lightning Web Components / Aura Components'
              run: npm run lint

            # LWC unit tests
            - name: 'Unit test Lightning Web Components'
              run: npm run test:unit:coverage

            # Upload code coverage data
            - name: 'Upload code coverage for LWC to Codecov.io'
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: LWC
